[package]
name = "serialization-size-dependent"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serialization-core = { path = "../core" }

either = "1.6"

[dev-dependencies]
parity-scale-codec = "3.1"
hex-literal = "0.3"
